In [90]:
import pandas as pd
import numpy as np
from apyori import apriori

In [91]:
data = pd.read_csv('Groceries_dataset.csv')

In [92]:
data

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  object
 2   itemDescription  38765 non-null  object
dtypes: int64(1), object(2)
memory usage: 908.7+ KB

In [94]:
data.describe()

       Member_number
count   38765.000000
mean     3003.641868
std      1153.611031
min      1000.000000
25%      2002.000000
50%      3005.000000
75%      4007.000000
max      5000.000000

In [95]:
df = pd.DataFrame(data)

In [96]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [97]:
sorted_df = df.sort_values(by="Member_number")
sorted_df

       Member_number        Date      itemDescription
1629            1000  27-05-2015                 soda
13331           1000  24-06-2014           whole milk
8395            1000  15-03-2015           whole milk
4843            1000  15-03-2015              sausage
17778           1000  27-05-2015   pickled vegetables
...              ...         ...                  ...
34885           5000  10-02-2015  semi-finished bread
25489           5000  16-11-2014     other vegetables
9340            5000  16-11-2014         bottled beer
27877           5000  09-03-2014               onions
3578            5000  10-02-2015                 soda

[38765 rows x 3 columns]

In [98]:
sorted_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38765 entries, 1629 to 3578
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  object
 2   itemDescription  38765 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.2+ MB

In [99]:
item_list = sorted_df.groupby(["Member_number","Date"])["itemDescription"].agg(lambda x : ','.join(x)).reset_index()

In [100]:
item_list

,Member_number,Date,itemDescription
0,1000,15-03-2015,"whole milk,sausage,yogurt,semi-finished bread"
1,1000,24-06-2014,"whole milk,salty snack,pastry"
2,1000,24-07-2015,"canned beer,misc. beverages"
3,1000,25-11-2015,"sausage,hygiene articles"
4,1000,27-05-2015,"soda,pickled vegetables"
...,...,...,...
14958,4999,24-01-2015,"yogurt,tropical fruit,kitchen towels,other veg..."
14959,4999,26-12-2015,"herbs,bottled water"
14960,5000,09-03-2014,"fruit/vegetable juice,onions"
14961,5000,10-02-2015,"root vegetables,semi-finished bread,soda"
14962,5000,16-11-2014,"other vegetables,bottled beer"

In [101]:
item_list.drop(["Member_number","Date"], axis=1,inplace =True)
item_list.columns = ['itemList']

In [102]:
item_df = pd.DataFrame(item_list)
item_df

                                                itemList
0          whole milk,sausage,yogurt,semi-finished bread
1                          whole milk,salty snack,pastry
2                            canned beer,misc. beverages
3                               sausage,hygiene articles
4                                soda,pickled vegetables
...                                                  ...
14958  yogurt,tropical fruit,kitchen towels,other veg...
14959                                herbs,bottled water
14960                       fruit/vegetable juice,onions
14961           root vegetables,semi-finished bread,soda
14962                      other vegetables,bottled beer

[14963 rows x 1 columns]

In [103]:
from collections import Counter

all_items = [item for sublist in item_df['itemList'].str.split(',') for item in sublist]

# Use Counter to count the frequency of each item
item_frequencies = Counter(all_items)

# Create a DataFrame from the Counter
item_frequency_df = pd.DataFrame(list(item_frequencies.items()), columns=['Item', 'Frequency'])

# Display the frequency of each item
print("Item Frequencies:")
item_frequency_df

Item Frequencies:

                     Item  Frequency
0              whole milk       2502
1                 sausage        924
2                  yogurt       1334
3     semi-finished bread        142
4             salty snack        283
..                    ...        ...
162        frozen chicken          5
163        salad dressing          6
164  specialty vegetables         11
165        toilet cleaner          5
166       rubbing alcohol          5

[167 rows x 2 columns]

In [104]:
transactions = item_frequency_df[['Item']].values.tolist()
transactions

[['whole milk'],
 ['sausage'],
 ['yogurt'],
 ['semi-finished bread'],
 ['salty snack'],
 ['pastry'],
 ['canned beer'],
 ['misc. beverages'],
 ['hygiene articles'],
 ['soda'],
 ['pickled vegetables'],
 ['curd'],
 ['frankfurter'],
 ['rolls/buns'],
 ['beef'],
 ['white bread'],
 ['whipped/sour cream'],
 ['other vegetables'],
 ['frozen vegetables'],
 ['butter'],
 ['sugar'],
 ['tropical fruit'],
 ['specialty chocolate'],
 ['butter milk'],
 ['detergent'],
 ['root vegetables'],
 ['dental care'],
 ['frozen meals'],
 ['dish cleaner'],
 ['cling film/bags'],
 ['frozen fish'],
 ['pip fruit'],
 ['chocolate'],
 ['red/blush wine'],
 ['shopping bags'],
 ['packaged fruit/vegetables'],
 ['margarine'],
 ['softener'],
 ['bottled water'],
 ['rice'],
 ['skin care'],
 ['chicken'],
 ['bottled beer'],
 ['flour'],
 ['liver loaf'],
 ['dessert'],
 ['hamburger meat'],
 ['liquor (appetizer)'],
 ['photo/film'],
 ['white wine'],
 ['domestic eggs'],
 ['herbs'],
 ['newspapers'],
 ['ketchup'],
 ['cocoa drinks'],
 ['canned fish'],
 ['coffee'],
 ['UHT-milk'],
 ['sliced cheese'],
 ['kitchen towels'],
 ['specialty bar'],
 ['candles'],
 ['curd cheese'],
 ['grapes'],
 ['candy'],
 ['citrus fruit'],
 ['onions'],
 ['brown bread'],
 ['processed cheese'],
 ['roll products '],
 ['meat'],
 ['mayonnaise'],
 ['mustard'],
 ['napkins'],
 ['hard cheese'],
 ['cookware'],
 ['fruit/vegetable juice'],
 ['soft cheese'],
 ['oil'],
 ['pet care'],
 ['long life bakery product'],
 ['beverages'],
 ['cake bar'],
 ['berries'],
 ['spices'],
 ['baking powder'],
 ['liquor'],
 ['male cosmetics'],
 ['fish'],
 ['ham'],
 ['cream cheese '],
 ['salt'],
 ['pork'],
 ['flower (seeds)'],
 ['pot plants'],
 ['ice cream'],
 ['waffles'],
 ['snack products'],
 ['cat food'],
 ['vinegar'],
 ['chewing gum'],
 ['Instant food products'],
 ['pasta'],
 ['prosecco'],
 ['chocolate marshmallow'],
 ['sweet spreads'],
 ['condensed milk'],
 ['house keeping products'],
 ['dishes'],
 ['female sanitary products'],
 ['popcorn'],
 ['dog food'],
 ['meat spreads'],
 ['spread cheese'],
 ['frozen fruits'],
 ['sauces'],
 ['rum'],
 ['finished products'],
 ['instant coffee'],
 ['artif. sweetener'],
 ['bathroom cleaner'],
 ['jam'],
 ['whisky'],
 ['pudding powder'],
 ['sparkling wine'],
 ['cream'],
 ['tea'],
 ['specialty fat'],
 ['specialty cheese'],
 ['frozen potato products'],
 ['turkey'],
 ['zwieback'],
 ['canned vegetables'],
 ['hair spray'],
 ['nut snack'],
 ['soups'],
 ['cereals'],
 ['seasonal products'],
 ['ready soups'],
 ['brandy'],
 ['light bulbs'],
 ['cleaner'],
 ['syrup'],
 ['canned fruit'],
 ['honey'],
 ['cooking chocolate'],
 ['abrasive cleaner'],
 ['liqueur'],
 ['frozen dessert'],
 ['organic sausage'],
 ['flower soil/fertilizer'],
 ['tidbits'],
 ['make up remover'],
 ['potato products'],
 ['bags'],
 ['preservation products'],
 ['baby cosmetics'],
 ['nuts/prunes'],
 ['soap'],
 ['decalcifier'],
 ['kitchen utensil'],
 ['organic products'],
 ['frozen chicken'],
 ['salad dressing'],
 ['specialty vegetables'],
 ['toilet cleaner'],
 ['rubbing alcohol']]

In [137]:
rules = apriori(transactions,min_support=0.001,min_confidance=0.2,min_lift=1,min_length=2)
rules

In [138]:
res = list(rules)
res

[RelationRecord(items=frozenset({'Instant food products'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Instant food products'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'UHT-milk'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'UHT-milk'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'abrasive cleaner'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'abrasive cleaner'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'artif. sweetener'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'artif. sweetener'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'baby cosmetics'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'baby cosmetics'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'bags'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'bags'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'baking powder'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'baking powder'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'bathroom cleaner'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'bathroom cleaner'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'beef'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'beef'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'berries'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'berries'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'beverages'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'beverages'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'bottled beer'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'bottled beer'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'bottled water'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'bottled water'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'brandy'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'brandy'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'brown bread'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'brown bread'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'butter'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'butter'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'butter milk'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'butter milk'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cake bar'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cake bar'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'candles'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'candles'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'candy'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'candy'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'canned beer'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'canned beer'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'canned fish'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'canned fish'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'canned fruit'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'canned fruit'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'canned vegetables'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'canned vegetables'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cat food'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cat food'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cereals'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cereals'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'chewing gum'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chewing gum'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'chicken'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chicken'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'chocolate'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chocolate'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'chocolate marshmallow'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chocolate marshmallow'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'citrus fruit'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'citrus fruit'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cleaner'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cleaner'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cling film/bags'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cling film/bags'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cocoa drinks'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cocoa drinks'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'coffee'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'coffee'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'condensed milk'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'condensed milk'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cooking chocolate'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cooking chocolate'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cookware'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cookware'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cream'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cream'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'cream cheese '}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cream cheese '}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'curd'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'curd'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'curd cheese'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'curd cheese'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'decalcifier'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'decalcifier'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'dental care'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'dental care'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'dessert'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'dessert'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'detergent'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'detergent'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'dish cleaner'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'dish cleaner'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'dishes'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'dishes'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'dog food'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'dog food'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'domestic eggs'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'domestic eggs'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'female sanitary products'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'female sanitary products'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'finished products'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'finished products'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'fish'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'fish'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'flour'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'flour'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'flower (seeds)'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'flower (seeds)'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'flower soil/fertilizer'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'flower soil/fertilizer'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frankfurter'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frankfurter'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen chicken'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen chicken'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen dessert'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen dessert'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen fish'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen fish'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen fruits'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen fruits'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen meals'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen meals'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen potato products'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen potato products'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen vegetables'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen vegetables'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'fruit/vegetable juice'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'fruit/vegetable juice'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'grapes'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'grapes'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'hair spray'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'hair spray'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'ham'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'ham'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'hamburger meat'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'hamburger meat'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'hard cheese'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'hard cheese'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'herbs'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'herbs'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'honey'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'honey'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'house keeping products'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'house keeping products'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'hygiene articles'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'hygiene articles'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'ice cream'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'ice cream'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'instant coffee'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'instant coffee'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'jam'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'jam'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'ketchup'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'ketchup'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'kitchen towels'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'kitchen towels'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'kitchen utensil'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'kitchen utensil'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'light bulbs'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'light bulbs'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'liqueur'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'liqueur'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'liquor'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'liquor'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'liquor (appetizer)'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'liquor (appetizer)'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'liver loaf'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'liver loaf'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'long life bakery product'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'long life bakery product'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'make up remover'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'make up remover'}), confidence=0.005988023952095809, lift=1.0)]),
 RelationRecord(items=frozenset({'male cosmetics'}), support=0.005988023952095809, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'male cosmetics'}), confidence=0.005988023952095809, lift=1.0)]),

In [139]:
df_results = pd.DataFrame(res)
df_results

,items,support,ordered_statistics
0,(Instant food products),0.005988,"[((), (Instant food products), 0.0059880239520..."
1,(UHT-milk),0.005988,"[((), (UHT-milk), 0.005988023952095809, 1.0)]"
2,(abrasive cleaner),0.005988,"[((), (abrasive cleaner), 0.005988023952095809..."
3,(artif. sweetener),0.005988,"[((), (artif. sweetener), 0.005988023952095809..."
4,(baby cosmetics),0.005988,"[((), (baby cosmetics), 0.005988023952095809, ..."
...,...,...,...
162,(white bread),0.005988,"[((), (white bread), 0.005988023952095809, 1.0)]"
163,(white wine),0.005988,"[((), (white wine), 0.005988023952095809, 1.0)]"
164,(whole milk),0.005988,"[((), (whole milk), 0.005988023952095809, 1.0)]"
165,(yogurt),0.005988,"[((), (yogurt), 0.005988023952095809, 1.0)]"
166,(zwieback),0.005988,"[((), (zwieback), 0.005988023952095809, 1.0)]"

In [140]:
df_results.describe()

          support
count  167.000000
mean     0.005988
std      0.000000
min      0.005988
25%      0.005988
50%      0.005988
75%      0.005988
max      0.005988

In [141]:
support = df_results.support

In [142]:
first_values = []
second_values = []
third_values = []
fourth_value = []

# loop number of rows time and append 1 by 1 value in a separate list.. first and second element was frozenset which need to be converted in list..
for i in range(df_results.shape[0]):
    single_list = df_results['ordered_statistics'][i][0]
    first_values.append(list(single_list[0]))
    second_values.append(list(single_list[1]))
    third_values.append(single_list[2])
    fourth_value.append(single_list[3])

In [143]:
lhs = pd.DataFrame(first_values)
rhs= pd.DataFrame(second_values)
confidance=pd.DataFrame(third_values,columns=['Confidance'])
lift=pd.DataFrame(fourth_value,columns=['lift'])

In [144]:
df_final = pd.concat([lhs,rhs,support,confidance,lift], axis=1)
df_final

                         0   support  Confidance  lift
0    Instant food products  0.005988    0.005988   1.0
1                 UHT-milk  0.005988    0.005988   1.0
2         abrasive cleaner  0.005988    0.005988   1.0
3         artif. sweetener  0.005988    0.005988   1.0
4           baby cosmetics  0.005988    0.005988   1.0
..                     ...       ...         ...   ...
162            white bread  0.005988    0.005988   1.0
163             white wine  0.005988    0.005988   1.0
164             whole milk  0.005988    0.005988   1.0
165                 yogurt  0.005988    0.005988   1.0
166               zwieback  0.005988    0.005988   1.0

[167 rows x 4 columns]